# Installing Julia

### Downloading the tarball
The recommended way to install jupyter is to unpack the tarball and use the binary there. The tarball can be found in the following link - 
https://julialang.org/downloads

### Using the binary
I have downloaded julia v1.9.3 for linux (64-bit glibc GPG) and unpacked the tarball in my home area. Inside the `bin` directory there is an executable binary named `julia`. You can either source the path to this bin folder by adding somthing like the following in your `.bashrc` -
```sh
export PATH="$PATH:/home/username/julia-1.9.3/bin"
```
OR include the binary in your `/usr/local/bin` by creating a symbolic link as shown below.
```sh
sudo ln -s /home/username/julia-1.9.3/bin /usr/local/bin/julia
```
I did the later.<br>
After this step, typing julia should bring you inside the julia prompt.

<img src="images/julia-prompt.png" alt="julia prompt" />

Julia scripts have a `.jl` extension, and can be executed just like python.
```sh
julia scriptname.jl
```
However, I like to use IJulia in jupyter notebook.

### Installing IJulia for jupyter
For using julia through notebook, you only need to install the interactive julia (IJulia). This can be done from the julia prompt.
```python
~>julia
julia>using Pkg
julia>Pkg.add("IJulia")
```

### Installing other packages
The following link contains the available julia packages. They can be installe din the same way as the above example.<br>
https://juliapackages.com/

---

# Hello-world

After installing IJulia, an additional option for kernel should be included in notebook.<br>
The `print()` function in Julia is used to display output without appending a newline character at the end, while `println()` is used to display output and append a newline character at the end.

In [1]:
print("Hello ")
print("world!")

Hello world!

In [2]:
println("Hello ")
println("world!")

Hello 
world!


# Comparing with python and C++
I found the following paper on arxiv which discusses Julia as a potential language for high energy physics.<br>
https://arxiv.org/abs/2306.03675

### Performance
Julia is designed to perform faster than python. It utilizes a just-in-time (JIT) compilation approach, which combines the best aspects of both interpreted and compiled languages. I picked up a plot from reddit, showing the time consumed by the different languages while calculating $\pi$.
<img src="images/julia-performance.jpg" alt="julia performance" width="50%"/>

### Variables

Let's look at some basic features of the variable types in Julia:

- **Dynamic Typing:** Julia is dynamically typed, just like python, meaning you don't need to declare the variable type explicitly.
- **Type Annotations:** Type annotations can be used to indicate the expected data type, but they are not enforced during runtime. For example, in python you can do - `x: int = 5`. In julia, you do the same by doing - `x::Int = 5`.
- **Type Conversion:**  Python allows for explicit type conversion using functions like `int()`, `float()`, `str()`, and others to convert variables from one type to another. Julia also supports these kind of type conversion with functions like `convert()`.
- **Single vs double quotes:** `" "` and `' '` have different meaning in julia. `" "` means `str` type, while `' '` is `char` type.
- Just like python, julia also has lists, arrays and dictionaries. The syntax is discussed later.

### Type conversions
In julia, 
- `parse(<type>, <string>)` function converts a string to any number type.
- `trunc(<type>, <float>)` converts floating point values to integers.
- `float(<int>)` converts integers to float.
- `string(<anytype>)` converts its arguments to string.

In [3]:
num = "12"
num = parse(Int64, num)
println("Type of the 'num' is $(typeof(num))")

floating = 3.7890
integer = trunc(Int64, floating)
println("Type of the 'integer' is $(typeof(integer))")

floating = float(integer)
println("Type of the 'floating' is $(typeof(floating))")

str = string(floating)
println("Type of the 'str' is $(typeof(str))")

Type of the 'num' is Int64
Type of the 'integer' is Int64
Type of the 'floating' is Float64
Type of the 'str' is String


> **Note :** f-string type string formatting is not available in julia. You have to use the dollar (\\$) symbol.<br>
> In this example, eveything within the brackets after the \\$ is a variable.

---

# Arrays

Let's start with 1D arrays first. In julia arrays, elements separated by commas/semicolons are arranged vertically. This is the default format for 1D-arrays. These are stored as `Vector` types. Similarly, elements separated by spaces are arranged horizontally. These are stored as `Matrix` (row) types. You can think of these as covariant and contravariant vectors from tensor analysis.

In [4]:
covariant_vector = [1 2 3] #row vector
contravariant_vector = [4 ; 5 ; 6] #column vector

println("We have the following covariant and contravariant vectors:")
display(covariant_vector)
display(contravariant_vector)

println("The type of the covariant vector in this example is $(typeof(covariant_vector))")
println("The type of the contravariant vector in this example is $(typeof(contravariant_vector))")

We have the following covariant and contravariant vectors:


1×3 Matrix{Int64}:
 1  2  3

3-element Vector{Int64}:
 4
 5
 6

The type of the covariant vector in this example is Matrix{Int64}
The type of the contravariant vector in this example is Vector{Int64}


> **Note :** With simple numbers, semicolon and comma are identical in arrays, but not in other cases. For example, if `A` is a matrix, then `[A,A]` is a vector of matrices, while `[A;A]` is a matrix combined (concatenated) from the two pieces.

You can also create undeclared arrays using `Array{type}(dims)` and empty arrays using `<type>[]`. For example,

In [5]:
arr = Array{Int64}(undef, 3) #undef means, values are random.
display(arr)

empty_arr = Int64[]
display(empty_arr)

3-element Vector{Int64}:
 140551019657200
 140551019644400
               1

Int64[]

### Creating arrays using range objects
- `collect(start:step:stop)` creates an array from `start` to `stop` in steps of `step`. This is similar to `range()` in python.
- The `range()` function is julia is more advanced. It gives you a `range` type object, which can be given as an input to a `collect()` function in order to get what you want. Consider the following two examples.

In [6]:
#Example 1 : Having a control over how many steps you want.
println("EXAMPLE 1")
range1 = range(1, length=5, stop=50) #Start from 1, end at 50 in EXACTLY 15 steps.
display(range1)
println("Type of this range object is - $(typeof(range1))")
println("It generates the following array -")
display(collect(range1))

#Example 2 : Having a control over the step-size.
println("EXAMPLE 2")
range2 = range(1, stop=55, step=10) #Start from 1, take steps of length 10, end at or before 55
display(range2)
println("Type of this range object is - $(typeof(range2))")
println("It generates the following array -")
display(collect(range2))

EXAMPLE 1


1.0:12.25:50.0

Type of this range object is - StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}
It generates the following array -


5-element Vector{Float64}:
  1.0
 13.25
 25.5
 37.75
 50.0

EXAMPLE 2


1:10:51

Type of this range object is - StepRange{Int64, Int64}
It generates the following array -


6-element Vector{Int64}:
  1
 11
 21
 31
 41
 51

### Creating arrays using comprehensions and generators
Once you have a range object, you can create an array by running a loop for the elements of the range. For example,

In [7]:
squared_integers = [n^2 for n in 1:5] #n=row
display(squared_integers)

#OR

twoD_ints = [n*m for n in 1:5, m in 1:4] #n=row, m=column
display(twoD_ints)

5-element Vector{Int64}:
  1
  4
  9
 16
 25

5×4 Matrix{Int64}:
 1   2   3   4
 2   4   6   8
 3   6   9  12
 4   8  12  16
 5  10  15  20

Given `m` and `n` dimensions (integers), you can also populate an array by doing `zeros(m, n)` or `ones(m, n)` or `rand(m, n)`. Checkout the other features of arrays here - https://www.tutorialspoint.com/julia/julia_arrays.htm

### Accessing elements of an array
- The element count starts with 1. That means, the first element is `arr[1]`.
- The last and the second-last elements are `arr[end]` and `arr[end-1]` respectively.
- Multiple elements can be accessed by giving a list of indiced as, `arr[[index1,index2,index3]]`.
- In case of 2D arrays, you can use `arr2D[row_index, col_index]`.
The following are woprking examples.

In [8]:
arr = [1 2 3 4 5]
display(arr)

println("The first element is = $(arr[1])")
println("The last element is = $(arr[end])")
println("The 2nd-last element is = $(arr[end-1])")
println("The 2nd and 3rd elements are = $(arr[[2,3]])")

arr2D = [1 2 ; 3 4; 5 6]
display(arr2D)
println("The element at location : row3, col2 is = $(arr2D[3, 2])")

1×5 Matrix{Int64}:
 1  2  3  4  5

The first element is = 1
The last element is = 5
The 2nd-last element is = 4
The 2nd and 3rd elements are = [2, 3]


3×2 Matrix{Int64}:
 1  2
 3  4
 5  6

The element at location : row3, col2 is = 6


### Pushing back and removing elements in 1D-arrays:
New elements can be pushed back at the end, first and at any index of an array by using the following functions.
- `push!(arr, ele)` : adds an element at the end.
- `pushfirst!(arr, ele)` : adds an element at the first.
- `splice!(arr, index, value)` : replaces an element at the given index.<br>
However, **these work for vertical arrays only.** (because horizontal arrays are of the `Matrix` type.)

In [9]:
arrv = [1; 2; 3; 4; 5]
println("Original array:")
display(arrv)

println("After pushing two values at the beginning and end:")
push!(arrv, 6)
pushfirst!(arrv, 0)
display(arrv)

println("After replacing the 5th element by 10")
splice!(arrv, 5, 10)
display(arrv)

Original array:


5-element Vector{Int64}:
 1
 2
 3
 4
 5

After pushing two values at the beginning and end:


7-element Vector{Int64}:
 0
 1
 2
 3
 4
 5
 6

After replacing the 5th element by 10


7-element Vector{Int64}:
  0
  1
  2
  3
 10
  5
  6

Without any argument, `splice(arr, index)` will simply remove the element at that index. Th functions `pop!()` and `popfirst!()` follows the same logic. Tuples can be used in the same way as python. I am not going to repeat that here.

---

# If, For, While and Functions

If conditions, for/while loops and functions behave the same as in python. **Indentation matters!**<br>
The syntax is just a bit different. The developers got rid of the annoying colon, and you need to mention the end.

### if, elseif, else
The basic syntax of julia if conditions is the following.
```julia
if boolean1
    #do somehting
elseif boolean2
    #do something else
else
    #do something else
end
```
The same logic is followed for the other things too.

### for loops
```julia
for i in <#=range object OR list/array=#>
    #do something
end
```

### while loops
```julia
while some_logic
    #do somehting
    #update logic
end
```

### Functions
```julia
function function_name(args)
    #expression
    #expression
    #expression
    #...
    #expression
end
```

---

# Dictionaries
This is the last basic thing I'll cover.<br>
The julia-syntax for a dictionary is a bit different from python. It has the following structure.<br>
`Dict(“key1” => value1, “key2” => value2,,…, “keyn” => valuen)`

In [10]:
dict = Dict("A"=>1, "B"=>2)

println("Here is a julia dictionary:")
display(dict)

#Adding another key:
dict["C"] = 3

println("Here is the same dictionary with another key,value pair added:")
display(dict)

Here is a julia dictionary:


Dict{String, Int64} with 2 entries:
  "B" => 2
  "A" => 1

Here is the same dictionary with another key,value pair added:


Dict{String, Int64} with 3 entries:
  "B" => 2
  "A" => 1
  "C" => 3

In julia, **the order of keys in a dictionary is not guaranteed.** When you print the dictionary, the order of the key-value pairs might not necessarily reflect the order in which they were added. If you need to maintain the order of elements, you might consider using an ordered dictionary implementation, such as the `OrderedDict` from the `DataStructures` package.

### Ordered dictionaries

In [11]:
using DataStructures

dict = OrderedDict("A"=>1, "B"=>2)
println("Here is an ordered dictionary:")
display(dict)

# Adding another key
dict["C"] = 3
println("Here is the same dictionary with another key,value pair added:")
display(dict)

Here is an ordered dictionary:


OrderedDict{String, Int64} with 2 entries:
  "A" => 1
  "B" => 2

Here is the same dictionary with another key,value pair added:


OrderedDict{String, Int64} with 3 entries:
  "A" => 1
  "B" => 2
  "C" => 3

Here are some features of dictionaries which will be handy later.
- Deleting a key : `delete!(dict, "key")`
- Getting a list of keys : `keys(dict)`
- Getting a list of values : `values(dict)`

### Looping over key-value pairs:

In [12]:
for kv in dict
    println(kv)
end

#Let's investigate one key-value pair:
for kv in dict
    println("\nThis is how a key-value pair looks like : $kv")
    println("It is of the type : $(typeof(kv))")
    println("key = $(kv[1])")
    println("value = $(kv[2])")
    break
end

"A" => 1
"B" => 2
"C" => 3

This is how a key-value pair looks like : "A" => 1
It is of the type : Pair{String, Int64}
key = A
value = 1


It is evident that kv is a tuple that contains each key-value pair. You can access the key and value just like the elements of a 1D array. You can perform the following operations on dictionaries:
- `union(dict1, dict2)`
- `intersect(dict1, dict2)`
- `setdiff(dict1, dict2)`
- `merge(dict1, dict2)`
.. etc

In [13]:
dict1 = OrderedDict("A"=>1, "B"=>2, "C"=>3, "D"=>4)
dict2 = OrderedDict("A"=>6, "D"=>4, "E"=>5)

united = union(dict1, dict2)
intersected = intersect(dict1, dict2)
diff = setdiff(dict1, dict2)
merged = merge(dict1, dict2)

println("The following 4 dictionaries are results of union, intersection, difference and merge respectively.")
display(united)
display(intersected)
display(diff)
display(merged)

The following 4 dictionaries are results of union, intersection, difference and merge respectively.


6-element Vector{Pair{String, Int64}}:
 "A" => 1
 "B" => 2
 "C" => 3
 "D" => 4
 "A" => 6
 "E" => 5

1-element Vector{Pair{String, Int64}}:
 "D" => 4

3-element Vector{Pair{String, Int64}}:
 "A" => 1
 "B" => 2
 "C" => 3

OrderedDict{String, Int64} with 5 entries:
  "A" => 6
  "B" => 2
  "C" => 3
  "D" => 4
  "E" => 5

I deliberately put a conflicting key `"A"` with two different values in these dictionaries to see what happens. It turns out that `union()` merges the two dictionaries while preserving the duplicate elements (without reordering the keys), while `merge()` replaces the values of any common keys from the second dictionary. `intersect()` only keeps the identical key-value pairs, and `setdiff` removes the common key-value pairs from the first dict.

I think this is enough for basics. In the [next notebook](2.%20Linear%20Algebra.ipynb), I am discussing some physics-motivated stuff.